name: Pull request
description: Supplementary information for a pull request.
title: "[Pull request]: "
labels: ["pr"]
body:
  - type: markdown
    attributes:
      value: |
        Branched code to be merged must be reviewed by the repo maintainers. Use this form to provide
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
###############################################################################
  - type: dropdown
    id: 
    attributes:
      label: Question
      options:
        - New feature
        - Enhancement
        - Bug fix
        - Security patch
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: Outline a list of key changes made to the code here, this will be populated in the changelog.
    validations:
      required: true
###############################################################################
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The code follows [Weaver Labs' style guide](https://github.com/weaver-lab/py-wiremq/blob/develop/docs/developerdocs/guides/CODE_STYLE_GUIDE.md)
          required: true
        - label: I have run the command `make test` and `make integration-test` and all tests pass
          required: true
        - label: For new features, I have written appropriate tests and provided configurations to demonstrate how the new feature works
          required: true
        - label: My code is well documented, with each class and method containing a docstring as per the style guide, quirky or difficult areas of code are well explained
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/weaver-lab/py-wiremq/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Weaver labs' Code of Conduct for pywiremq
          required: true
