name: Bug Report
description: 🐞🐞 File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to file a bug report.
        Please first check the issue board to see if your issue has already been addressed.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
###############################################################################
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a brief overview of what is causing the issue and what the result was.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expect to happen?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: configurations
      description: If using custom configurations, please provide these so the issue can be reproduced.
###############################################################################
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What build version of the library are you using?
    validations:
      required: true
  - type: textarea
    id: python-version
    attributes:
      label: What version of Python are you running?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste relevant log output here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/weaver-lab/py-wiremq/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Weaver labs' Code of Conduct for pywiremq
          required: true
