name: Failing Test Report
description: 🐞🐞 File a report of a failing test. Tests are run using either `make test` for unit tests, or `make integration-test` for integration tests.
title: "[Failing test]: "
labels: ["failing", "test"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to file a report about a test that is failing.
        Please first check the issue board to see if your issue has already been addressed.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
###############################################################################
  - type: dropdown
    id: test-type
    attributes:
      label: Test type
      description: Is the failing test a unit test or an integration test?
      options:
        - Unit test
        - Integration test
  - type: textarea
    id: which-test
    attributes:
      label: Which test file?
      placeholder: e.g. wiremq.routers.threaddispatcher
    validations:
      required: true
  - type: textarea
    id: test-method
    attributes:
      label: Which test(s) failed?
      placeholder: e.g. test_threaddispatcher
    validations:
      required: false
  - type: dropdown
    id: test-type
    attributes:
      label: Test type
      description: Is the failing test a unit test or an integration test?
      options:
        - Unit test
        - Integration test
  - type: textarea
    id: test-method
    attributes:
      label: Which test(s) failed?
      placeholder: e.g. test_threaddispatcher
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output.
      description: Paste relevant log output here.
      render: shell
###############################################################################
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What build version of the library are you using?
    validations:
      required: true
  - type: textarea
    id: python-version
    attributes:
      label: What version of Python are you running?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste relevant log output here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/weaver-lab/py-wiremq/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Weaver labs' Code of Conduct for pywiremq
          required: true
