name: Feature request
description: 🐞🐞 Submit a request for a new feature.
title: "[Feature request]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to point out a security issue to the development team. If possible, enough information should be provided here to reproduce the issue.
        Please first check the issue board to see if your issue has already been addressed.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
###############################################################################
  - type: textarea
    id: component
    attributes:
      label: Title
      description: A brief summary of the proposed new feature.
      placeholder: e.g. New endpoint type
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe in more detail the proposed new feature.
    validations:
      required: true
###############################################################################
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/weaver-lab/py-wiremq/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Weaver labs' Code of Conduct for pywiremq
          required: true
