name: Enhancement request
description: 🐞🐞 Submit a request for the enhancement of an existing component.
title: "[Enhancement request]: "
labels: ["enhancement", "modification"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request a change to an existing py-wiremq component. For requests about entirely new features, please use the Feature Request form.
        Please first check the issue board to see if your issue has already been addressed.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
###############################################################################
  - type: textarea
    id: component
    attributes:
      label: Title
      description: A brief summary of the proposed enhancement.
      placeholder: e.g. Improved handling of XYZ in Base Channel.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe in more detail the proposed enhancement.
    validations:
      required: true
###############################################################################
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/weaver-lab/py-wiremq/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Weaver labs' Code of Conduct for pywiremq
          required: true
