name: Question Support
description: 🐞🐞 Ask the support team a general question.
title: "[Question Support]: "
labels: ["support"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to submit a question to the support team which is not covered by the other issue types.
        Please first check the issue board to see if your issue has already been addressed.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g. email@example.com
    validations:
      required: false
###############################################################################
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
###############################################################################
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/weaver-lab/py-wiremq/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow Weaver labs' Code of Conduct for pywiremq
          required: true
