# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build pywiremq

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install Maria CS repository
      run: |
       wget https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
       sudo chmod +x mariadb_repo_setup
       sudo ./mariadb_repo_setup --mariadb-server-version="mariadb-10.6"

    - name: Install dependencies
      run: |
        sudo apt-get install libmariadb3 libmariadb-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Start MongoDB
      run: |
        sudo docker run --name mongo-gh -d -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=weaverusr -e MONGO_INITDB_ROOT_PASSWORD=weaverpass -e MONGODB_INITDB_DATABASE=weaverdb mongo
    
    - name: Start MariaDB
      run: |
        sudo docker run --name mariadb-gh -d -p 5432:5432 -e MARIADB_ROOT_USER=weaverusr -e MARIADB_ROOT_PASSWORD=weaverpass -e MARIADB_DATABASE=weaverdb mariadb

#      uses: supercharge/mongodb-github-action@1.8.0
#      with:
#        mongodb:-username: weaverusr
#        mongodb-password: weaverpass
#        mongodb-db: weaverdb
#        mongodb-version: '6.0'
    - name: Test with pytest
      run: |
        pytest
